### ISSUE TITLE
class helper

### ISSUE THREAD

**Issue by Featuresgtp** [RomanYankovsky/DelphiAST#105]
It is impossible to distinguish a class helper, and descendant of the class.
eg (https://www.dropbox.com/sh/v5dkbg0wtlag13y/AAAltxYWKkivalB0JeNdedhFa?dl=0)

    TNewTestClass = class(TTestClass)
    end;
    TTestClassHelper = class helper for TTestClass
    end;

**Comment by RomanYankovsky** [comment]
That information is missing now. I will fix this issue soon. Thanks for letting me know.

**Comment by RomanYankovsky** [comment]
Try the latest source. It produces the different AST for these cases:
```xml
      <TYPEDECL line="9" col="1" name="TNewTestClass">
        <TYPE line="9" col="17" type="class">
          <TYPE line="9" col="23" name="TTestClass"/>
        </TYPE>
      </TYPEDECL>
      <TYPEDECL line="11" col="1" name="TTestClassHelper">
        <TYPE line="11" col="20" type="class">
          <HELPER line="11" col="26">
            <TYPE line="11" col="37" name="TTestClass"/>
          </HELPER>
        </TYPE>
      </TYPEDECL>
```

**Comment by vintagedave** [comment]
That shows TTestClassHelper as a class.  Is it?  Should its type be
"helper" not "class"?
