### ISSUE TITLE
Default property value

### ISSUE THREAD

**Issue by Featuresgtp** [RomanYankovsky/DelphiAST#106]
After the last commit was no parse properties with default values, eg (https://www.dropbox.com/s/t6dcss7g3jrgysm/uTest.pas?dl=0)

    TTestClass = class
    public
        function Getcount : integer;
        property Count : integer read Getcount default 0;
    end;

Error: 'End' expected found '0'

**Comment by RomanYankovsky** [comment]
@Wosi please review. I changed the way it represents default properties in the tree.

**Comment by Wosi** [comment]
That looks good. I didn't even know about the possibility to define default values. Is there any official documentation about all language features? Even after spending several years in different Delphi projects I explore new language features every couple of months.
