### ISSUE TITLE
DFM files support

### ISSUE THREAD

**Issue by JayDi85** [RomanYankovsky/DelphiAST#107]
Can you add DFM-files support in your parser?

**Comment by RomanYankovsky** [comment]
Most likely this not going to happen. DelphiAST is a pascal parser. We must stay focused.

If you need a DFM parser, I suggest to a look at this project https://github.com/masonwheeler/DFMJSON

**Comment by NickRing** [comment]
I came across this http://cc.embarcadero.com/Item/23141 (while looking for something else). Don't know how useful it is...
