### ISSUE TITLE
{$i-} directive is incorrectly handled as an include directive, causing an exception

### ISSUE THREAD

**Issue by vintagedave** [RomanYankovsky/DelphiAST#110]
{$i-} and {$i+} control whether exceptions are thrown when an error occurs using old-style file IO.  http://www.delphibasics.co.uk/RTL.asp?Name=$I

However, DelphiAST treats them as an include directive.  There are two bugs:

1. They are treated as an include directive. It tries to open a blank filename in the current directory, which fails and throws.
2. The exception thrown is a EFOpenError, not a ESyntaxTreeException. This means the syntax tree up to that point isn't available, and also means anyone copying the demo code, which checks for ESyntaxTreeException only, is going to get an unhandled exception.  Not sure what's best here, but perhaps external code like that could be caught and wrapped into an ESyntaxTreeException?  Or is it expected in normal operation that other exception types can be thrown?

Simple unit to reproduce:

unit FalseInclude;

interface

implementation

procedure FileIO;
begin
  {$i-} // Error here
    // Insert old-style file IO... Reset, etc.
  {$i+}
end;

end;

**Comment by NickRing** [comment]
The problem is with in "function TmwBasePasLex.GetDirectiveKind: TptTokenKind;"

A small change seems to fix it. From:


```
  case KeyHash of
    9:
      if KeyComp('I') then
        Result := ptIncludeDirect else 
        Result := ptCompDirect;
```

to:

```
  case KeyHash of
    9:
      if KeyComp('I') and (not CharInSet(FOrigin[Run], ['+', '-'])) then
        Result := ptIncludeDirect else 
        Result := ptCompDirect;
```

**Comment by RomanYankovsky** [comment]
Thanks, @NickRing :)
