### ISSUE TITLE
Parameter string type

### ISSUE THREAD

**Issue by Featuresgtp** [RomanYankovsky/DelphiAST#124]
The latest version is a duplication of the type in method ("string.string"):

procedure AddError(const AError : string);

          <METHOD begin_line="13" begin_col="9" end_line="14" end_col="5" kind="procedure" name="AddError">
            <PARAMETERS line="13" col="27">
              <PARAMETER line="13" col="34" kind="const">
                <NAME line="13" col="34" value="AError"/>
                <TYPE line="13" col="43" name="string.string"/>
              </PARAMETER>
            </PARAMETERS>
          </METHOD>

**Comment by RomanYankovsky** [comment]
Related issue #86
