### ISSUE TITLE
Fails to parse code with ^\

### ISSUE THREAD

**Issue by alisterchristie** [RomanYankovsky/DelphiAST#134]
Exception of the following code (which Delphi compiles) - it doesn't like the `\^`
```pascal
procedure TMyForm.FormKeyPress(Sender: TObject; var Key: Char);
begin
   if Key = ^\ then 
   begin
      //some code
   end;
end;
```

**Comment by NickRing** [comment]
procedure TmwBasePasLex.PointerSymbolProc; (in SimpleParser.Lexer) needs updating to include '\' (and any other possible characters):
{code}  if CharInSet(FOrigin[Run], ['a'..'z','A'..'Z', '\']) and not IsIdentifiers(FOrigin[Run+1]) then{code}

**Comment by RomanYankovsky** [comment]
Hm. What are other possible characters?

**Comment by NickRing** [comment]
The following characters need to be added: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
