### ISSUE TITLE
Is there someway to avoid problems with .inc ? 

### ISSUE THREAD

**Issue by rfrezino** [RomanYankovsky/DelphiAST#154]
Hi everybody,
  I'm creating a project to replace the current Delphi FindUnit. 
  By now a lot of things are working, but I'm facing some problems to load the whole library available.
  One good example is the JCL library. I list all the .pas files on it's directory and parse them using DelphiAST, but I get messages like:
Cannot open file "C:\Rodrigo\Programacao\Componentes Delphi XE\JEDI\jvcl\run\crossplatform.inc". The system cannot find the specified file. 

I noticed that DelphiAst always look for inc on the same folder of the pas it's working with. Is possible to say to it look on library path for this file ? Or create some alternative to it ? 

Thanks too much

**Comment by rfrezino** [comment]
I had an idea. 
I can pass as parameter a list with all my available incs (A Tstringlist, with all incs paths) to the parser. If the parser need to get some inc and didn't find it in the same folder as the pas it consult on the list.
What do you think ?

**Comment by RomanYankovsky** [comment]
You need to write your own implementation of IIncludeHandler interface. See demo project for an example.

**Comment by RomanYankovsky** [comment]
@rfrezino can I close?
