### ISSUE TITLE
Parser fails on parameter names with dots

### ISSUE THREAD

**Issue by Wosi** [RomanYankovsky/DelphiAST#155]
I'm surprised again by Delphi's syntax.
Parsing `System.Classes.pas` for Delphi XE6 fails here:

    TGetModuleProc = procedure(const FileName, UnitName, FormName,
      DesignClass: string; CoSystem.Classes: TStrings) of object;

**Comment by RomanYankovsky** [comment]
OMG. How is this expected to work?

**Comment by Wosi** [comment]
I'm sorry, I don't know what I did yesterday night. I assume I accidently broke the Delphi sources on my machine a couple of days ago. Shame on me.
