### ISSUE TITLE
Symbol Tree

### ISSUE THREAD

**Issue by LK-Daniel** [RomanYankovsky/DelphiAST#156]
Hi, I'm picking up the torch from my friend Simon, whom had written a fairly complete Symbol Tree for DelphiAST.

I'm updating it to build properly with the latest DelphiAST changes, and will then submit a Pull Request to integrate it into the official repo.

Submitting as an issue for the sake of "tracking", since I can't assign Tags to the issue, this should be marked as an "Enhancement".

I intend to have this committed for review and integration within the week.

**Comment by vintagedave** [comment]
That's very interesting news! I had heard he had written one, and I have
bits of an incomplete one around as well.

**Comment by vintagedave** [comment]
Is there a branch somewhere I can see the existing code?

**Comment by LK-Daniel** [comment]
I'm going through a large backlog of Simon's uncommitted code (it's a long story as to why this task has fallen to me now) and ensuring they each work against the latest revisions of their respective repositories before committing them.

This will be going in the "LaKraven" Fork of DelphiAST soon as I have it working with the large number of DelphiAST changes made after his implementation was added (he was working with an older revision).
Once it compiles and passes testing, I'll commit it and submit a Pull Request.

According to his checklist, he also planned to produce and provide a series of precompiled Symbol Table files for Delphi versions 2007 to 10 Seattle, so that those with Pro SKU licenses (with no source for RTL, VCL and FMX units) can still use the Symbol Table fully. That work will follow shortly after I commit the Symbol Tree code as it takes time to produce all of these for each version of Delphi.

There's also a bug in his DPROJ Interpreter code I need to figure out. Looks like he hadn't refined that particular unit before I ended up inheriting the sources.

**Comment by LK-Daniel** [comment]
His approach was actually pretty clever. I see a huge note in his pad here saying "NOT A BLOODY TABLE! IT'S A TREE!" and under that a fairly simple diagram showing how to resolve a given Symbol to to a specific scope (Unit > Type > Symbol for example).

I can see that his approach requires a list of Unit Paths to be passed along, and clearly he's extracting these from a given DPROJ file based on the Platform and Config, inherited along the Build Config chain.

He also wrote a small Demo Project which is what I'm trying to get building against the latest DelphiAST revision now.

**Comment by vintagedave** [comment]
A tree is how mine works as well. In fact, and this is still unimplemented, my Resolve() method takes a context which represents, say, a method. The idea is to resolve a symbol you need to know from where you're resolving it, so you can work upwards through the local variables, method parameters, class, unit, then uses. Then the symbol table for each unit is a tree, so a context really represents a collection item inside a unit's tree.

It's not done yet, which is why I'm interesting in Simon's.

**Comment by vintagedave** [comment]
BTW I read your G+ post about how you're taking over from Simon. I hope he's doing well. Thanks for picking up for him.

**Comment by LK-Daniel** [comment]
Simon's works exactly that way (stepping up through the nodes from a given "local scope" where present, then back down in turn through the "Unit Symbols" to see if it can resolve it in any one of those).

It provides a means of "Absolute Resolution" (which is where a Symbol only resolves if it is "visible" within a given "Local Scope") as well as "Non-Contextual Resolution" (where a given Symbol resolves to one or many regardless of whether or not the Scope of that Symbol is visible to a given "Local Scope").
He's also written a "quick and dirty" plugin for the Code Editor which can make suggestions when your code references a Symbol defined in a scope not visible to the current "Local Scope". By that I mean that it can say "Hey, the Symbol '%s' is defined in the following Unit(s) '%s', would you like to add a Uses reference to one of these Units?" then presents a Context Menu list of said Unit(s), clicking any one of which will inject the reference into the "Uses" section in the most appropriate scope (Interface or Implementation, respectively).

It looks like a clever idea, but definitely needs some polishing before it can be made available publicly.

**Comment by vintagedave** [comment]
> ""Hey, the Symbol '%s' is defined in the following Unit(s) '%s', would
you like to add a Uses reference to one of these Units?""

That's the goal of my symbol table too, to write a plugin that does exactly
that. I may have left it too late if one already exists :/

**Comment by LK-Daniel** [comment]
I've noticed that a lot of Simon's ideas in his huge stack of "Project Notes" seem like common-sense. I've been surprised that the RAD Studio IDE doesn't already have a lot of these features integrated directly.

**Comment by Wosi** [comment]
@LK-Daniel First of all it's great that you overtake and open source Simon's symbol tree project.
But I have a bad feeling about making a pull request to this repository. Why?

- The DelphiAST project says about itself to be an "Abstract syntax tree builder for Delphi". A symbol tree is a huge project on top of DelphiAST. This repository would lose its clear purpose. Until now it has got a single responsibility. This makes maintenance easy. That would change when adding a symbol tree here.

- Structural changes in DelphiAST would become much harder to commit when the symbol tree takes place in this repository. Whenever somebody wants to pull a useful change to the DelphiAST project he would need to change the symbol tree project as well even though the developer has no idea how it works internally. When applying all of Delphi's language constructs to the symbol tree you would result in a **much bigger** project than DelphiAST. I know what I'm talking about. Applying DelphiAST modifications to the symbol tree can take hours even for developers who know the sources.

- Not everybody needs a symbol table when working with DelphiAST

I recommend to open a new GitHub repository for the symbol tree and use DelphiAST as a submodule. The project maintainers can evaluate each change in DelphiAST and modify the sources separately. Structural changes in this repository would not automatically break the symbol tree project.

**Comment by LK-Daniel** [comment]
Well, @Wosi, I'll leave that up to @RomanYankovsky to decide. I can set up a stand-alone repository for the Symbol Tree, or I can submit a pull request for the official repository.
The Symbol Tree is actually fairly simple in terms of its structure and implementation, and like any good library it doesn't modify (in any way) the DelphiAST units it consumes to do its work. That means you aren't forced to include the Symbol Tree in your projects if you don't need to use it.

I do agree that it could, potentially, add a small amount of extra work should the public interfaces of the DelphiAST itself change... though I would hope that significant public interface changes in the DelphiAST itself won't be happening all that often (it's generally considered a "bad" thing to break public interfaces).

Ultimately not my decision to make. If @RomanYankovsky would rather it be integrated into DelphiAST, that's what Simon's project notes state as his original intention. If not, then I'll make a separate GitHub repository for it as I'm pretty sure that's what Simon would do.

**Comment by RomanYankovsky** [comment]
@LK-Daniel Let's start with small steps... Please put it on github, make it compile and then we will see how to integrate pieces together.

**Comment by LK-Daniel** [comment]
I've created a new repository called "DelphiAST-Extra" into which I'll be putting the Symbol Tree along with the DPROJ Interpreter.

**Comment by vintagedave** [comment]
Sounds great. Why not "DelphiSymbolTable" as a project name?

Can I ask you guys, off topic - I'm wondering about the ethics of using
this code for my uses-clause plugin. I have been working on a symbol table
on and off for a while intending to use it for a plugin that handles the
uses cause, but I don't have a plugin yet. (I was intending to sell it,
like Navigator.) I feel rather like if I used this to do so, I'd be taking
advantage of Simon's work.

**Comment by LK-Daniel** [comment]
It's called "DelphiAST-Extra" because it doesn't just include the Symbol Tree, it also includes a DPROJ interpreter to extract all of the options for all of the build configurations (it also provides an interface to modify them and save the project).

As well, it's going to provide pre-parsed Symbol Trees for the RTL, VCL and (where applicable) FMX libraries for every version of Delphi.
This is absolutely essential for people using Starter and Pro SKUs where the Sources aren't available. At the moment I'm working on a utility to determine which of the Symbols parsed from the Enterprise SKUs  for each version apply to the lower SKUs (because not all features are provided in the lower SKUs)
For Delphis 2010 to 10 Seattle, this is can be done automagically... but for older versions I do not have the necessary RTTI.

As-to whether it would be ethical to make use of this Symbol Tree in your commercial plugin... there's nothing in the DelphiAST license structure to prohibit you from doing so.

**Comment by RomanYankovsky** [comment]
> As well, it's going to provide pre-parsed Symbol Trees for the RTL, VCL and (where applicable) FMX libraries for every version of Delphi.

Are you sure it's legal? It almost the same as putting RTL, VCL and FMX sources on github.

**Comment by LK-Daniel** [comment]
It's illegal to republish their source, but not a map saying "this symbol, which belongs to this symbol (etc) can be found on line x, column y"

**Comment by vintagedave** [comment]
Why publish the map - why not publish the code to generate the map, instead? Then anyone can run it for any version they are using.
