### ISSUE TITLE
Parser fails at attribute in interface directly after guid

### ISSUE THREAD

**Issue by sglienke** [RomanYankovsky/DelphiAST#19]
The following code will fail with error: 'End' expected found '['

unit Unit1;

interface

type
  IFoo = interface
    ['{F208B04E-2612-4E64-8728-1A94A1D19C27}']
    [Test]
    procedure Test;
  end;

implementation

end.

P.S. It also fails for 2 attributes following each other.

**Comment by LaKraven** [comment]
Well, that's no great shock given that Custom Attributes aren't supported in Delphi, and even EMBT's compiler will flag the warning W1025 "Unsupported Language Feature"

**Comment by sglienke** [comment]
Eh? It has nothing to do with that. W1025 is triggered when the attribute class is not found because the unit its declared in is missing while this bug just fails to parse two following things with square brackets.
