### ISSUE TITLE
Method Resolution Clause will not parsed correct

### ISSUE THREAD

**Issue by ProHolz** [RomanYankovsky/DelphiAST#195]
If i have a type like these
```
type

  IInterface1 = interface
    function Init: Boolean; stdcall;
  end;

  IInterface2 = interface
    function Init: Boolean; stdcall;
  end;

  IInterface3 = interface
    function Init: Boolean; stdcall;
  end;

  TTestClass = class(TInterfacedObject, IInterface1, IInterface2, IInterface3)
  private
    function I2Init: Boolean; stdcall;
    function I3Init: Boolean; stdcall;

  public
    function Init: Boolean; stdcall; 
    function IInterface2.Init = I2Init;
    function IInterface3.Init = I3Init;
  end;
```
The resulting AST is 

```
<METHOD begin_line="26" begin_col="5" end_line="27" end_col="5" name="IInterface2.Init"/>
<METHOD begin_line="27" begin_col="5" end_line="28" end_col="3" name="IInterface3.Init"/>
```

**Comment by Wosi** [comment]
It's implemented on my fork. 

The AST looks like that:

            <METHOD begin_line="26" begin_col="5" end_line="27" end_col="5">
              <RESOLUTIONCLAUSE line="26" col="5" name="IInterface2.Init">
                <NAME line="26" col="33" value="I2Init"/>
              </RESOLUTIONCLAUSE>
            </METHOD>
            <METHOD begin_line="27" begin_col="5" end_line="28" end_col="3">
              <RESOLUTIONCLAUSE line="27" col="5" name="IInterface3.Init">
                <NAME line="27" col="33" value="I3Init"/>
              </RESOLUTIONCLAUSE>
            </METHOD>

There's [this pull request ](https://github.com/RomanYankovsky/DelphiAST/pull/194 ) pending.  @RomanYankovsky Are there any problem with that PR?

**Comment by ProHolz** [comment]
Thanks i will try it

**Comment by RomanYankovsky** [comment]
@Wosi merged right now. Sorry, I'm a bit busy during last weeks.

**Comment by ProHolz** [comment]
Thanks for the Patch, it works great
