### ISSUE TITLE
How to compile with FPC?

### ISSUE THREAD

**Issue by leiradel** [RomanYankovsky/DelphiAST#199]
I'm trying to build a simple command-line utility that parses a `.pas` file and writes its AST to stdout, but I can't compile DelphiAST with FPC.

My current cmdline is:

```
fpc -Fu../../DelphiAST/Source -Fu../../DelphiAST/Source/SimpleParser -Fu../../DelphiAST/Source/FreePascalSupport -Fu../../DelphiAST/Source/FreePascalSupport/FPC_StringBuilder/Src -Fu../../DelphiAST/Source/FreePascalSupport/Generics.Collection/src -O2 -Mobjfpc -SfANSISTRINGS DelphiParser.pas
```
 But I'm stuck at this error:

```
DelphiAST.pas(2022,25) Error: Incompatible types: got "TPasSyntaxTreeBuilder.ParserMessage(TObject;const TMessageEventType;const AnsiString;LongInt;LongInt);" expected "<procedure variable type of procedure(TObject;const TMessageEventType;const ShortString;LongInt;LongInt) of object;Register>"
```

If I comment that line, I get these one instead:

```
StringBuilderUnit.pas(77,23) Error: Illegal type conversion: "ShortString" to "PChar"
StringBuilderUnit.pas(117,30) Error: Illegal type conversion: "ShortString" to "PChar"
```

which makes me think I'm doing something wrong WRT strings. Any help is appreciated.

**Comment by RomanYankovsky** [comment]
@Wosi can you please take a look?

**Comment by Wosi** [comment]
Seems there's a problem with the command line parameters. The error in `DelphiAST.pas(2022,25)` looks like you are not using mode `Delphi` to compile the file. Does it work if you remove `-Mobjfpc` from command line?

The errors in `StringBuilderUnit.pas` indicate you are using an old build configuration where `String = ShortString`. I don't know how to change it via command line. 

Can you compile `DelphiASTDemo.lpi` using Lazarus?
There are some additional defines which may be important. These are: `-dBorland -dVer150 -dDelphi7 -dCompiler6_Up -dPUREPASCAL`

I usually don't use `FPC` directly. I rather use `lazbuild` to compile the project. If you can compile a project with lazarus then you will get it also via `lazbuild SomeProjectFolder\SomeProject.lpi`.

**Comment by leiradel** [comment]
Thanks guys, Lazarus compiled `DelphiASTDemo.lpi` just fine. I'll change it to a console program and continue using Lazarus.

**Comment by abulka** [comment]
@leiradel I'm trying to do the same thing as you and output an ast to stdout. I git cloned this project, opened the `ParserDemo.lpi` project using Lazarus 2.0.6 and got errors re `Windows` and `Generics.Collections` being missing (am on a Mac). 

Perhaps I need to compile on Windows to avoid the windows error. As for `Generics.Collections` I understand that free pascal has a different generics implementation to Delphi - not sure what an empty `Source/FreePascalSupport/Generics.Collection` directory is doing in this DelphiAST project?

You seem to have compiled `DelphiASTDemo.lpi` which I cannot find. Is this part of your own personal project? Did you end up succeeding in your project and do you happen to have anything you can share?

**Comment by leiradel** [comment]
@abulka sorry, it's been a long time and I can't recall any specifics about this.

What I do remember is that the parser couldn't parse my Pascal source code so I ended up using my own ad hoc parser.

**Comment by RomanYankovsky** [comment]
@leiradel it's a Delphi parser, thus it doesn't fully support all FPC syntax. Sorry.

It can be compiled with FPC though, thanks @Wosi for help https://github.com/RomanYankovsky/DelphiAST/issues/289

**Comment by leiradel** [comment]
@RomanYankovsky my Pascal files were actually Delphi source code. Unfortunately I don't remember the specifics. Now everything that I needed to parse and convert is already done via my ad hoc parser.

**Comment by abulka** [comment]
I managed to create a command line prototype version that even runs on Mac (and thus probably Linux).  Attached are the files, which I dropped in the `Demo/Parser` directory and compiled with
```
'/usr/local/bin/fpc'  -MDelphi -Scghi -O1 -gw2 -godwarfsets -gl -l -vewnhibq -Fi../../Source -Fi../../Source/SimpleParser -Fi../../Source/FreePascalSupport/Generics.Collections/src -Fu../../Andy -Fu../../Source -Fu../../Source/FreePascalSupport/FPC_StringBuilder/Src -Fu../../Source/FreePascalSupport/Generics.Collection/src -Fu../../Source/FreePascalSupport -Fu../../Source/SimpleParser -Fu/Developer/lazarus/lcl/units/x86_64-darwin/cocoa -Fu/Developer/lazarus/lcl/units/x86_64-darwin -Fu/Developer/lazarus/components/lazutils/lib/x86_64-darwin -Fu/Developer/lazarus/packager/units/x86_64-darwin -Fu. -oparsecli -dLCL -dBorland -dVer150 -dDelphi7 -dCompiler6_Up -dPUREPASCAL parsecli.pas
```
not sure which of the above flags are really necessary, but they come from the original Lazarus project.  

Note the output file is specified as `-oparsecli` thus the resulting program is `parsecli`.  I haven't implemented passing the filename as a parameter to the program yet.  

@RomanYankovsky I'm wanting to traverse the AST - not sure whether to read in the XML and traverse that in Python (my preferred language) - or traverse a `TSyntaxNode`  directly in Pascal.  If you have any advice, it would be appreciated.

[parsecli_prototype.zip](https://github.com/RomanYankovsky/DelphiAST/files/3883315/parsecli_prototype.zip)
