### ISSUE TITLE
Address compiler warnings/hints

### ISSUE THREAD

**Issue by LaKraven** [RomanYankovsky/DelphiAST#21]
For the sake of "best practise", I've addressed all of the hints and warnings raised within the Castalia parser.

These are fixed in my fork here: https://github.com/LaKraven/DelphiAST

No other changes have been made beyond appropriately resolving these hints/warnings (no "hide and forget" tactics used there)

**Comment by RomanYankovsky** [comment]
Thanks! Just create a pull request and I will merge it.

**Comment by RomanYankovsky** [comment]
Merged.
