### ISSUE TITLE
Add Defines by Default for XE to XE8, and other Platforms

### ISSUE THREAD

**Issue by LaKraven** [RomanYankovsky/DelphiAST#22]
I've added support in my fork (https://github.com/LaKraven/DelphiAST) for the default defines in SimpleParser.Lexer.pas for (TmwBasePasLex.InitDefines) for newer Delphi versions, as well as other platforms (Android, iOS, MacOSX, Win64)

These should be merged over into the official repository.

**Comment by RomanYankovsky** [comment]
Ok, just create a pull request and I will merge it.

**Comment by LaKraven** [comment]
Request created... thanks.

I'll create additional requests as I make additional changes/additions/improvements.

I very-much appreciate your work on DelphiAST! It's a very useful backbone for code automation tools!

**Comment by RomanYankovsky** [comment]
Merged :)
