### ISSUE TITLE
Retracted: Uses with explicit path are not supported: uses x in 'c:\myunit.pas';

### ISSUE THREAD

**Issue by JBontes** [RomanYankovsky/DelphiAST#243]
Retracted, Delphi only supports `in` uses in programs or libraries.

**Comment by Wosi** [comment]
Why do you think it's not supported? It works fine in current master.

**Comment by JBontes** [comment]
It ignores the 'in' part. 
Hardly supported. 

Kind regards,

-- Johan Bontes

**Comment by Wosi** [comment]
How can it ignore the `in`? The filepath is actually present in the AST.
It looks like this:

`<UNIT line="7" col="3" name="uMainForm" path="uMainForm.pas"/>`

What are you missing?

**Comment by JBontes** [comment]
Oops, must have broken something in my version. Let me check and correct the error. 

Thanks for the heads up. 

Kind regards,

-- Johan Bontes

**Comment by JBontes** [comment]
Yes, you are right the `uses x in 'path'` is only allowed in `program` or `library`, not in an `implementation` or `interface` uses. I'll fix the commit.
