### ISSUE TITLE
Need list of all comments

### ISSUE THREAD

**Issue by PeterPanino** [RomanYankovsky/DelphiAST#292]
I need a list of all the comments in the unit. Unfortunately, comments currently are not parsed.

**Comment by RomanYankovsky** [comment]
Actually, comments are parsed. Check `TPasSyntaxTreeBuilder.Comments` right after parsing. There is a lost of all comments in unit.

**Comment by PeterPanino** [comment]
How can I extract the comment STRINGS from **TPasSyntaxTreeBuilder.Comments**?

**Comment by RomanYankovsky** [comment]
I have updated ParserDemo, take a look.

**Comment by PeterPanino** [comment]
Roman, thank you very much!

What would you suggest as the FASTEST parser for the XML? For example, to get a list of all strings in the unit?

**Comment by PeterPanino** [comment]
I have added a `Strings` property to `TPasSyntaxTreeBuilder`. In this way, I can get all the strings in the unit easily inside a single string. What do you think about the implementation? Is it correct?
[DelphiAST.zip](https://github.com/RomanYankovsky/DelphiAST/files/3950800/DelphiAST.zip)

**Comment by PeterPanino** [comment]
I have now also added a `Numbers` property to `TPasSyntaxTreeBuilder`. In this way, I can get all the numbers in the unit easily inside a single string. What do you think about the implementation? Is it correct?
[DelphiAST 11.12.2019 16.08.zip](https://github.com/RomanYankovsky/DelphiAST/files/3951028/DelphiAST.11.12.2019.16.08.zip)

**Comment by RomanYankovsky** [comment]
Looks correct. 

I'm just curious, why do you need all strings and numbers?

**Comment by PeterPanino** [comment]
I plan to create a semantic database of Delphi source files.

**Comment by PeterPanino** [comment]
See also the issue of missing end-position information in comment nodes.

**Comment by RomanYankovsky** [comment]
Ok, this one is resolved.
