### ISSUE TITLE
Possible string mismatch?

### ISSUE THREAD

**Issue by PeterPanino** [RomanYankovsky/DelphiAST#296]
I have this code line inside a unit:

![image](https://user-images.githubusercontent.com/5140376/70867311-69ce0c00-1f74-11ea-80df-a2b445c98de8.png)

In the syntax tree, this line results as:

`<LITERAL line="47" col="35" value="ab&apos;cd" type="string"/>`

You can see that the LITERAL value `ab&apos;cd` is not correct?

**Comment by PeterPanino** [comment]
You can see that the double single quote from the source is replaced by an APOSTROPHE HTML Entity in the syntax tree?

**Comment by RomanYankovsky** [comment]
But this is XML. Special symbols have to be encoded. If this is a problem, you may use a tree of `TSyntaxNode` directly without serializing them to XML.
