### ISSUE TITLE
Parser fails on System.pas

### ISSUE THREAD

**Issue by sglienke** [RomanYankovsky/DelphiAST#34]
Tried with XE6 and XE7.

'Begin' expected, found 'end'

**Comment by RomanYankovsky** [comment]
Please download the latest sources. Then make sure that you defined a platform's defines before parsing. This was fine for me (tested with XE7):
```delphi
      ASTBuilder.AddDefine('MSWINDOWS');
      ASTBuilder.AddDefine('CPUX86');
```
Please confirm that it works for you now :)

**Comment by LaKraven** [comment]
Using latest version of your demo, @RomanYankovsky, parsing XE7's System.pas unit... I'm getting the same error as @sglienke.

The line it's failing on is 5442, and appears to be related to the Defines not being handled properly. I'm checking to see if this has anything to do with my modifications to the conditional defines handling, but it shouldn't because these are {$IFDEF} expressions not {$IF DEFINED(CONDITION)} (which is what I improved for you the other day).

I'll make the code break on IFDEF expressions only when Y > 5415 and step through the code to see where it's going wrong.

**Comment by RomanYankovsky** [comment]
I guess that's because demo doesn't define CPUX86.

**Comment by LaKraven** [comment]
Extra bit of information, and this is a strange one.
Looking at the Lexer's FDefined list at the point of failure, the list is completely empty!

CPUX86' define is definitely in there (I added it myself along with all the other standard compiler defines up to XE7's list, which was in the merge you did from my pull request the other day).

**Comment by LaKraven** [comment]
Okay, why is there an "Exit" call on line 2331 of SimpleParser.Lexer.pas? This means that none of the necessary defines are being added to the Lexer's FDefines list!

**Comment by LaKraven** [comment]
Removing that "Exit" call from line 2331 makes it parse all the way up to line 39592 with a different error.

**Comment by RomanYankovsky** [comment]
Please make sure that you have merged latest changes. Empty define list was fixes yesterday with commit 7c061bbd86f10d2bace67d2bfb3ac56bcd3954ab, and default defines were moved to other method with commit 7b5d5af91734cec8ad043dd5e96fb956b6cfe615.

**Comment by RomanYankovsky** [comment]
Also I updated the demo a couple of minutes ago. Now it's fine.

P.S. I moved default defines to other method because it's not always needed. For instance, you may run parser on Windows machine, but want to parse Android code. Especially, if you develop an IDE expert.

**Comment by LaKraven** [comment]
I accidentally pulled from my fork instead of the upstream. Pulling from the upstream it now parses (and takes a VERY long time to produce the XML)

**Comment by RomanYankovsky** [comment]
Yup. Actually parser is fast (less than a second to parse System.pas on my laptop), but converting a tree of TSyntaxNode to XML takes A LOT of time...

**Comment by LaKraven** [comment]
It's a massive unit, so it doesn't surprise me that generating all of that XML data takes a significant amount of time. For my purposes, that's not a problem as I'm not using the XML output, but rather the TSyntaxNode directly.

**Comment by RomanYankovsky** [comment]
Fixed.
