### ISSUE TITLE
Type name can be in either a node attribute or a child node - should be one or the other

### ISSUE THREAD

**Issue by vintagedave** [RomanYankovsky/DelphiAST#58]
When parsing a 'type' section, the AST records the type name of a type differently when the class is a type vs when it's anything else (record etc.)

For classes, the name of the type is an attribute 'name'.

For records, the name of the type is in a child node with node name 'type'.

So, for example, parsing code:
type
  TFoo = class
  end;

  TBar = record
  end;

  TAbc = Integer;

The syntax node for the first (TFoo) will have an attribute 'type' with value 'TFoo'. The second and third (TBar, TAbc) will have child nodes with node names 'type', with name attribute 'TBar' or 'TAbc'.

I am happy to fix this but am not sure which alternative is better.  (Personally, I lean towards the first behaviour, having the type name as an attribute for the typedecl node. A whole new child node seems overkill to me, unless it may contain other information in future.)

**Comment by RomanYankovsky** [comment]
I agree, new child not seems overkill. But also please note, that the following case is possible. Thus classes/interfaces may have an attribute _and_ a child node.
```delphi
type
  TIntList = class(TList<Integer>)
  end;
```
```xml
  <TYPEDECL line="9" col="1" name="TFoo2" type="class">
    <TYPE line="9" col="15" name="TList">
      <TYPEARGS line="9" col="21">
        <TYPE line="9" col="21" name="Integer"/>
      </TYPEARGS>
    </TYPE>
  </TYPEDECL>
```
Do you agree? I can work on this, but also I'll be happy if you fix this :)

**Comment by vintagedave** [comment]
Having a child node for the ancestor / inherited-from type makes sense - in fact, if there is a child node for the name of the type itself, that could get potentially confusing.

So, for the name of the type that is being declared, a 'name' attribute is the best solution?  Then type child nodes would indicate inheritance.

I haven't done any coding at all in DelphiAST yet and I'm keen to fix at least one bug, or add one feature, just to get into the codebase. Unless this is urgent or likely to be very difficult to fix, would you mind if I had a go at working on it?

**Comment by RomanYankovsky** [comment]
Yes, go ahead :)

**Comment by LaKraven** [comment]
Nice one for diving in head first @vintagedave :)

**Comment by vintagedave** [comment]
I am afraid I have not had time to look at this yet. I don't want to hold
it up; Roman, if you want to change it please do. I'll pick something else
for my first commit :)
