### ISSUE TITLE
Multidimensional array-constant's expression list not separated by dimensions

### ISSUE THREAD

**Issue by polyaklaci** [RomanYankovsky/DelphiAST#63]
At a multidimensional array-constant definition e.g.:
```pascal
const
  SAMPLE: array[1..2, 2..3] of String = ( ( 'a', 'b' ), ( 'c', 'd' ) );
```
the generated expression list for the RHS value is 'continuous', the 'dimensional-breaks' are lost.
(EXPR('a') - EXPR('b') - EXPR('c') - EXPR('d') is generated in AST)

Suggested solution:
Override **ArrayConstant** method in **TPasSyntaxTreeBuilder** class, with the next code:
```pascal
procedure TPasSyntaxTreeBuilder.ArrayConstant;
begin
  FStack.Push(sROUNDOPEN);
  try
    inherited;
  finally
    FStack.Pop;
  end;
end;
```
which will 'insert' ** ROUNDOPEN** tags at 'dimensional-breaks'. The generated AST nodes will be:
RO - RO - EXPR('a') - EXPR('b') - RO/ - RO - EXPR('c') - EXPR('d') - RO/ - RO/

Two remarks:
- ROUNDOPEN is just an 'acceptable' tag, it can be for example 'EXPRESSIONS' tag (or something else).
- The constant-dimension definitions is parsed well by DelphiAST (and one can know the expression list dimension boundaries from it), but I write a 'Delphi to JavaScript' compiler (I use the DelphiAST for this purpose), and the dimension expressions can be 'complicated' (can be any kind of constant expression,  which value can not be evaluated at AST parsing). So the best way I think is to add the expression list boundaries explicit to the AST.

**Comment by RomanYankovsky** [comment]
Thank you!
