### ISSUE TITLE
How do I check the calling convention of a method?

### ISSUE THREAD

**Issue by JBontes** [RomanYankovsky/DelphiAST#74]
I want to extract all methods in a unit that have the <code>stdcall</code> calling convention.  
This so that I can get the definition of dll methods in the WinAPI.  

However I do not see a <code>TSyntaxNodeType</code> called <code>ntCallingConvention</code>, nor does the Method have a calling convention attribute.  

Is there a way to get to the calling convention of a method?

**Comment by RomanYankovsky** [comment]
Unfortunately, it's not implemented yet.
It's not a big deal though, I will try to pay attention to this issue in the next few days.

**Comment by RomanYankovsky** [comment]
Done :)
See the new callingconvention attribute in METHOD nodes
```xml
    <METHOD line="35" col="17" name="someExperimentalProc" kind="procedure" callingconvention="safecall">
```

**Comment by JBontes** [comment]
Hi Roman,

Thanks for responding so quickly.  
I love the project and can see that you've been working hard to make it.  
I have a number of suggestions to improve, but I would like to suggest these in the form of source
code rather than requests.  

Directives
*******************
I noticed that there is no support for directives in DelphiAST.  
Looking at how the system works I've figured out how to add them, but I'm wondering how to proceed.  

A. I can add a new `directives` Child with a bunch of `directive` in it (just like the `parameters`) to the `ntMethod` node.
due to the number of directives possible, this seems like the cleanest option.

B. I can add these as attributes to the base ntMethod node. 

What would be your recommendation?
I'll upload the code as soon as I get something working. 


Additional features
********************
I've noticed that you cannot 'walk' the tree.  
So I've made some tweaks to FindNode.
I've got some more idea's, but that'll have to wait.  


Performance
*********************
I've put the parser through an instrumenting profiler, to see where the time
is spend.  I'll see if I can make some speedups.

Now I need to figure out how to best to setup Delphi to work with github.

Will get back later.

Kind regards,

-- Johan

 
  _____

**Comment by RomanYankovsky** [comment]
> I noticed that there is no support for directives in DelphiAST.

Personally, I'd prefer to use attributes. Yes, there are a lot of different directives possible, but usually there are only a few of them used. Also some directives like 'override' are already in attributes. 

> So I've made some tweaks to FindNode.

Ok

> I've put the parser through an instrumenting profiler, to see where the time is spend.  I'll see if I can make some speedups.

That would be great!

> Now I need to figure out how to best to setup Delphi to work with github.

I use the official github client. It does not has the integration with Delphi, but anyways, I like it. It is available at https://windows.github.com/

**Comment by JBontes** [comment]
Shouldn't this issue be closed?
