### ISSUE TITLE
'Initialization', 'finalisation' and 'exports' are not supported

### ISSUE THREAD

**Issue by vintagedave** [RomanYankovsky/DelphiAST#77]
A unit containing 'initialization' and 'finalization' has the code in each of those sections inside a generic 'statements' node.

'exports' doesn't even do that, but throws an exception.

For example,

```
...
initialization
  Hello;

finalization
  Hello;

exports
  Hello;

end.
```

**Comment by RomanYankovsky** [comment]
As far as I know you cannot put Exports clause *after* Initialization/Finalization. Try to compile this.

**Comment by vintagedave** [comment]
You're right - but just found that when I put it before the initialization, it completely ignores the statement.

Code:
```
unit Unit1;

interface

implementation

procedure Foo;
begin

end;

exports
  Foo;

initialization
  Foo;

finalization
  Foo;

end.
```

Output:
```
<?xml version="1.0"?>
<UNIT line="1" col="1" name="Unit1">
  <INTERFACE line="3" col="1"/>
  <IMPLEMENTATION line="5" col="1">
    <METHOD line="7" col="1" name="Foo" kind="procedure">
      <STATEMENTS end_line="10" begin_line="10" end_col="1" begin_col="1"/>
    </METHOD>
  </IMPLEMENTATION>
  <STATEMENTS end_line="18" begin_line="16" end_col="1" begin_col="3">
    <CALL line="16" col="3">
      <IDENTIFIER line="16" col="3" name="Foo"/>
    </CALL>
  </STATEMENTS>
  <STATEMENTS end_line="21" begin_line="19" end_col="1" begin_col="3">
    <CALL line="19" col="3">
      <IDENTIFIER line="19" col="3" name="Foo"/>
    </CALL>
  </STATEMENTS>
</UNIT>
```

Note that:
 * There is no entry for the exports at all - it goes straight from the method Foo to the statements that represent the init/finalization.
* The empty method Foo has a wrong begin_line - it says both begin_line and end_line are 10, but the begin_line is 8.

**Comment by RomanYankovsky** [comment]
Get the latest sources. The issue with initialization/finalization/exports is fixed :)

**Comment by RomanYankovsky** [comment]
I see the issue with begin/end position. I'll look into it.

**Comment by vintagedave** [comment]
That's a separate issue so I should probably have put it in a separate bug report.  I just noticed it looking at that code.

**Comment by RomanYankovsky** [comment]
:+1:
