### ISSUE TITLE
Add support for `warning` directives

### ISSUE THREAD

**Issue by JBontes** [RomanYankovsky/DelphiAST#83]
Add support for the warning/hinting directives. 

Hinting Directives The 'hint' directives <code>platform</code>, <code>deprecated</code>, and <code>library</code> may be appended to any declaration. These directives will produce warnings at compile time. Hint directives can be applied to type declarations, variable declarations, class, interface, and structure declarations, field declarations within classes or records, procedure, function, and method declarations, and unit declarations. 

When a hint directive appears in a unit declaration, it means that the hint applies to everything in the unit. For example, the Windows 3.1 style OleAuto.pas unit on Windows is completely deprecated. Any reference to that unit or any symbol in that unit produces a deprecation message. 

The platform hinting directive on a symbol or unit indicates that it may not exist or that the implementation may vary considerably on different platforms. The library hinting directive on a symbol or unit indicates that the code may not exist or the implementation may vary considerably on different library architectures. 

The platform and library directives do not specify which platform or library. If your goal is writing platform-independent code, you do not need to know which platform a symbol is specific to; it is sufficient that the symbol be marked as specific to some platform to let you know it may cause problems for your goal of portability.

**Comment by JBontes** [comment]
procedure TPasSyntaxTreeBuilder.DirectiveDeprecated;
    var
      DeprecatedText: string; 
    begin
      FStack.Push(ntConstant,false);
      try
        inherited;
        if FStack.Peek.HasChildren then
          DeprecatedText:= FStack.Peek.ChildNodes[0].GetAttribute(atValue)
        else
          DeprecatedText:= '';
      finally
        FStack.Pop;
      end;
      FStack.Peek.SetAttribute(atDeprecated, DeprecatedText);
    end;

    procedure TPasSyntaxTreeBuilder.DirectiveLibrary;
    begin
      FStack.Peek.SetAttribute(atLibraryHint, 'true');
      inherited;
    end;

    procedure TPasSyntaxTreeBuilder.DirectivePlatform;
    begin
      FStack.Peek.SetAttribute(atPlatform, 'true');
    end;

**Comment by JBontes** [comment]
Roman, is there a reason you don't want to merge the code. If so can you pls close this issue?

**Comment by RomanYankovsky** [comment]
Hm. I was thinking I have merged it. Didn't I? Let me check.

**Comment by JBontes** [comment]
Yes you did. So this issue can be closed.
