### ISSUE TITLE
Methods with generic parameters are not fully parsed.

### ISSUE THREAD

**Issue by GallaherMike** [RomanYankovsky/DelphiAST#85]
This declaration...

procedure SetModifiedBy(const Value: Nullable<string>);

...produces...

            <METHOD line="283" col="5" kind="procedure" name="SetModifiedBy">
              <PARAMETERS line="283" col="28">
                <PARAMETER line="283" col="35" kind="const">
                  <NAME line="283" col="35" value="Value"/>
                  <TYPE line="283" col="42" name="Nullable"/>
                </PARAMETER>
              </PARAMETERS>
            </METHOD>

The expectation is that the TYPE would have a TYPEARGS child collection with a TYPE node in that collection similar to the way field declarations are parsed.

Field example below.

FModifiedBy : Nullable<string>;

yields...

            <FIELD line="43" col="5">
              <NAME line="43" col="5" value="FModifiedBy"/>
              <TYPE line="43" col="18" name="Nullable">
                <TYPEARGS line="43" col="27">
                  <TYPE line="43" col="27" name="string"/>
                </TYPEARGS>
              </TYPE>
            </FIELD>

**Comment by JBontes** [comment]
The funny thing is that the declaration of var sections and method parameters is remarkably similar. However the parsing is very different.  
Will see if I can unify the two.

**Comment by GallaherMike** [comment]
It seems like you got the gist of the problem anyway, but I copied the wrong starting string. The property declaration is actually.

procedure SetModifiedBy(const Value: Nullable<String>);

**Comment by RomanYankovsky** [comment]
I guess it was 
```delphi
procedure SetModifiedBy(const Value: Nullable<string>);
```
:)
