### ISSUE TITLE
Error parsing SimpleParser.pas

### ISSUE THREAD

**Issue by QweZxc25** [RomanYankovsky/DelphiAST#96]
Parsing SimpleParser.pas by DelphiAST produce error
''Implementation'' expected found ''{$INCLUDE SimpleParser.inc}''

**Comment by RomanYankovsky** [comment]
Hm, cannot reproduce this with demo app. Do you use the latest sources?

**Comment by QweZxc25** [comment]
I found the problem - the Demo used IIncludeHandler. Becouse I have used the TPasSyntaxTreeBuilder.Run with stream, I didn't set it - and this produced the error.
Sorry for inconvenience

**Comment by sglienke** [comment]
You can reproduce this when you have code from before the addition of the include handler whic probably looks like this:

TPasSyntaxTreeBuilder.Run(FileName)

When providing a default value (in this case nil for the IIncludeHandler) I expect it can still properly parse an include directive (it just does not go into the file and parse it). But currently it just fails.
